name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Test
      run: echo "Pipeline dummy test passed!"

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build . --file Dockerfile --tag test:${{ github.run_number }}

    - name: Push additional image tag
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push test:${{ github.run_number }}

    - name: Checkout Other Repository
      uses: actions/checkout@v2
      with:
        repository: other-repo-owner/other-repo-name
        ref: main # or specify the branch you want

    - name: Update Deployment YAML
      run: |
        sed -i 's|image: your-dockerhub-username/your-image-name:old-tag|image: your-dockerhub-username/your-image-name:new-tag|' path/to/your/deployment.yaml

    - name: Commit and Push Changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
        git add path/to/your/deployment.yaml
        git commit -m "Update deployment.yaml with latest build"
        git push

    - name: Logout from Docker Hub
      run: docker logout